# ------------------------------
# 適当にuserを作る
# ------------------------------

---
- hosts: all
  sudo: true
  user: ansible


  tasks:
    - name: add group
      group:
       name: unix
       gid: 2000

    - name: add user
      user: 
       name: sato
       home: /home/sato
       group: unix
       uid: 2001
       password: "{{ 'test'|password_hash('sha512') }}"

